# Generated by Django 5.2.5 on 2025-09-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Ítem')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('is_bonifiable', models.BooleanField(default=True, verbose_name='Es Bonificable')),
            ],
            options={
                'verbose_name': 'Ítem Facturable',
                'verbose_name_plural': 'Ítems Facturables',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('status', models.CharField(choices=[('PEN', 'Pendiente de Pago'), ('VER', 'En Verificación'), ('PAG', 'Pagado'), ('BON', 'Bonificado')], default='PEN', max_length=3, verbose_name='Estado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.billableitem', verbose_name='Ítem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='members.profile')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='receipts/', verbose_name='Comprobante de Pago')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='billing.invoice')),
            ],
        ),
    ]
