# Generated by Django 5.2.5 on 2025-09-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
