# Generated by Django 5.2.5 on 2025-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board_members/', verbose_name='Foto')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Miembro de la Directiva',
                'verbose_name_plural': 'Miembros de la Directiva',
                'ordering': ['display_order'],
            },
        ),
    ]
