# Generated by Django 5.2.5 on 2025-09-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board_members/', verbose_name='Foto')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden')),
                ('group', models.CharField(choices=[('Mesa Directiva', 'Mesa Directiva'), ('Vocales', 'Vocales'), ('Comisión Fiscalizadora', 'Comisión Fiscalizadora')], default='Mesa Directiva', max_length=50, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Miembro de la Directiva',
                'verbose_name_plural': 'Miembros de la Directiva',
                'ordering': ['group', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Cita o Testimonio')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('relation', models.CharField(help_text='Ej: Padre de jugador Sub-15, Socio Fundador, Jugadora de Primera', max_length=100, verbose_name='Relación con el Club')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto (Opcional)')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar para que este testimonio pueda aparecer en la página de inicio.', verbose_name='Destacar en Inicio')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Hito')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history_images/', verbose_name='Imagen')),
                ('exact_date', models.DateField(blank=True, null=True, verbose_name='Fecha Exacta (Opcional)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='core.timelineevent', verbose_name='Hito Padre (si es un sub-hito)')),
            ],
            options={
                'verbose_name': 'Hito de la Historia',
                'verbose_name_plural': 'Hitos de la Historia',
                'ordering': ['year'],
            },
        ),
    ]
