# Generated by Django 5.2.5 on 2025-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['group', 'display_order'], 'verbose_name': 'Miembro de la Directiva', 'verbose_name_plural': 'Miembros de la Directiva'},
        ),
        migrations.AddField(
            model_name='boardmember',
            name='group',
            field=models.CharField(choices=[('Mesa Directiva', 'Mesa Directiva'), ('Vocales', 'Vocales'), ('Comisión Fiscalizadora', 'Comisión Fiscalizadora')], default='Mesa Directiva', max_length=50, verbose_name='Grupo'),
        ),
    ]
