# Generated by Django 5.2.5 on 2025-08-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_boardmember_options_boardmember_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Hito')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history_images/', verbose_name='Imagen del Hito')),
                ('event_type', models.CharField(choices=[('HITO', 'Hito Principal'), ('SUB', 'Sub-Hito')], default='HITO', max_length=4, verbose_name='Tipo de Evento')),
                ('order', models.PositiveIntegerField(default=0, help_text='Para ordenar eventos dentro del mismo año', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Hito de la Historia',
                'verbose_name_plural': 'Hitos de la Historia',
                'ordering': ['year', 'order'],
            },
        ),
    ]
