# Generated by Django 5.2.5 on 2025-08-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timelineevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year'], 'verbose_name': 'Hito de la Historia', 'verbose_name_plural': 'Hitos de la Historia'},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='order',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='core.timelineevent', verbose_name='Hito Padre (si es un sub-hito)'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history_images/', verbose_name='Imagen'),
        ),
    ]
