# Generated by Django 5.2.5 on 2025-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='exact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Exacta (Opcional)'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
    ]
