# Generated by Django 5.2.5 on 2025-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timelineevent_exact_date_timelineevent_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Cita o Testimonio')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('relation', models.CharField(help_text='Ej: Padre de jugador Sub-15, Socio Fundador, Jugadora de Primera', max_length=100, verbose_name='Relación con el Club')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto (Opcional)')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar para que este testimonio pueda aparecer en la página de inicio.', verbose_name='Destacar en Inicio')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['author'],
            },
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='subtitle',
        ),
    ]
