# Generated by Django 5.2.5 on 2025-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial_remove_timelineevent_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL de Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL de Twitter/X')),
                ('youtube_url', models.URLField(blank=True, verbose_name='URL de YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='URL de TikTok')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
    ]
