# Generated by Django 5.2.5 on 2025-09-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL de Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL de Twitter/X')),
                ('youtube_url', models.URLField(blank=True, verbose_name='URL de YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='URL de TikTok')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Ingresar solo números, ej: 5492964123456', max_length=20, verbose_name='Número de WhatsApp')),
            ],
            options={
                'verbose_name': 'Redes Sociales',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
