# Generated by Django 5.2.5 on 2025-08-29 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_category_player_managed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Equipo')),
                ('shield_image', models.ImageField(blank=True, null=True, upload_to='team_shields/', verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles Local')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles Visitante')),
                ('match_datetime', models.DateTimeField(verbose_name='Fecha y Hora del Partido')),
                ('venue', models.CharField(blank=True, max_length=150, verbose_name='Estadio o Lugar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='players.category', verbose_name='Categoría del Club')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fixtures.team', verbose_name='Equipo Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fixtures.team', verbose_name='Equipo Local')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['match_datetime'],
            },
        ),
    ]
