# Generated by Django 5.2.5 on 2025-09-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Equipo')),
                ('shield_image', models.ImageField(blank=True, null=True, upload_to='team_shields/', verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles Local')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles Visitante')),
                ('match_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora del Partido')),
                ('venue', models.CharField(blank=True, max_length=150, verbose_name='Estadio o Lugar')),
                ('league_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la Liga')),
                ('tournament_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Torneo')),
                ('stage', models.CharField(blank=True, max_length=100, verbose_name='Etapa del Torneo')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='members.category', verbose_name='Categoría del Club')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fixtures.team', verbose_name='Equipo Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fixtures.team', verbose_name='Equipo Local')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['display_order', 'match_datetime'],
            },
        ),
    ]
