# Generated by Django 5.2.5 on 2025-08-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='stage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etapa del Torneo'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del Torneo'),
        ),
    ]
