# Generated by Django 5.2.5 on 2025-08-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixture_stage_fixture_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='match_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora del Partido'),
        ),
    ]
