# Generated by Django 5.2.5 on 2025-08-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_alter_fixture_match_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['display_order', 'match_datetime'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AddField(
            model_name='fixture',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden'),
        ),
    ]
