# Generated by Django 5.2.5 on 2025-08-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_alter_fixture_options_fixture_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='league_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre de la Liga'),
        ),
    ]
