# Generated by Django 5.2.5 on 2025-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_fixture_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Marcar para que este partido aparezca en la página de inicio.', verbose_name='Destacado en Inicio'),
        ),
    ]
