# Generated by Django 5.2.5 on 2025-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Sponsor')),
                ('logo', models.ImageField(upload_to='sponsors/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='URL del Sitio Web (Opcional)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
