# Generated by Django 5.2.5 on 2025-09-05 16:41

import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Socio')),
            ],
            options={
                'verbose_name': 'Tipo de Socio',
                'verbose_name_plural': 'Tipos de Socio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecificPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo Específico',
                'verbose_name_plural': 'Cargos Específicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.PositiveIntegerField(default=members.models.get_next_member_id, editable=False, unique=True, verbose_name='Número de Socio')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil')),
                ('extra_photo_1', models.ImageField(blank=True, null=True, upload_to='extra_photos/', verbose_name='Foto Extra 1 (opcional)')),
                ('extra_photo_2', models.ImageField(blank=True, null=True, upload_to='extra_photos/', verbose_name='Foto Extra 2 (opcional)')),
                ('dni_photo_front', models.ImageField(blank=True, null=True, upload_to='dni_photos/', verbose_name='Foto DNI (Frente)')),
                ('dni_photo_back', models.ImageField(blank=True, null=True, upload_to='dni_photos/', verbose_name='Foto DNI (Dorso)')),
                ('is_on_roster', models.BooleanField(default=False, verbose_name='En Lista Oficial (para jugadores)')),
                ('is_exempt', models.BooleanField(default=False, verbose_name='Cuota Bonificada')),
                ('member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membertype', verbose_name='Tipo de Socio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('JUG', 'Jugador'), ('STA', 'Cuerpo Técnico'), ('DIR', 'Dirigente')], max_length=3, verbose_name='Función')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.category', verbose_name='Categoría (si aplica)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='members.profile')),
                ('specific_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.specificposition', verbose_name='Cargo Específico')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
