# Generated by Django 5.2.5 on 2025-09-02 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACT', 'Activo (Cuota al día)'), ('ATR', 'Atrasado'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado de la Cuota')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Último Pago')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Próximo Vencimiento')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.profile', verbose_name='Perfil del Socio')),
            ],
            options={
                'verbose_name': 'Estado de Membresía',
                'verbose_name_plural': 'Estados de Membresías',
            },
        ),
    ]
