# Generated by Django 5.2.5 on 2025-09-04 20:34

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='extra_photos/', verbose_name='Foto Extra 1 (opcional)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='extra_photos/', verbose_name='Foto Extra 2 (opcional)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_id',
            field=models.PositiveIntegerField(default=members.models.get_next_member_id, editable=False, unique=True, verbose_name='Número de Socio'),
        ),
    ]
