# Generated by Django 5.2.5 on 2025-09-02 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='receipts/', verbose_name='Comprobante de Pago')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.profile')),
            ],
            options={
                'verbose_name': 'Pago Registrado',
                'verbose_name_plural': 'Pagos Registrados',
                'ordering': ['-payment_date'],
            },
        ),
    ]
