# Generated by Django 5.2.5 on 2025-09-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_profiles',
            field=models.ManyToManyField(blank=True, to='members.profile', verbose_name='Vínculos (ej: hijos a cargo)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_type',
            field=models.CharField(choices=[('JUG', 'Socio Jugador'), ('PAD', 'Socio Padre/Tutor'), ('DIR', 'Socio Dirigente'), ('ADH', 'Socio Adherente')], default='ADH', max_length=3, verbose_name='Tipo de Socio'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Pago'),
        ),
    ]
