# Generated by Django 5.2.5 on 2025-08-27 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Foto')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('birth_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad de Nacimiento')),
                ('birth_province', models.CharField(blank=True, max_length=100, verbose_name='Provincia de Nacimiento')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Posición')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('member_id', models.CharField(blank=True, max_length=50, verbose_name='Número de Socio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
        ),
    ]
