# Generated by Django 5.2.5 on 2025-08-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Arquero', 'Arquero'), ('Defensor', 'Defensor'), ('Mediocampista', 'Mediocampista'), ('Delantero', 'Delantero'), ('Director Técnico', 'Director Técnico'), ('Ayudante de Campo', 'Ayudante de Campo'), ('Preparador Físico', 'Preparador Físico')], max_length=50, verbose_name='Posición'),
        ),
    ]
